### PR TITLE
Add local jquery and jquery-ui files

### PR DESCRIPTION
**Pull request by TokinRing**
Rather than pulling jquery and jquery-ui from the internet, having the files locally will help for piclusters not connected to the internet. 

I know that these files are usually cached and not pulled during every request, but if I am troubleshooting issues in the web browser and need to clear my cache from time to time while not online, I ould like to still be able to use the app.

### CODE REVIEW

**Comment by rusher81572** [comment]
@TokinRing 
The following files are now broken and cause errors in Chrome:

manage.html
terminal.html
addhost.html
removehost.html
addcontainer.html

```
Uncaught TypeError: $(...).dialog is not a function
    at manage.html:176
```

**Comment by rusher81572** [comment]
Also, the following files still reference jquery that is not local:

```
MacBook-Pro:web rusher81572$ grep '//' *.html
addhost.html:	<script src="//assets/jquery-1.10.2.js">
addhost.html:	<link rel="stylesheet" href="//assets/jquery-ui.css">
addhost.html:	<script src="//assets/jquery-ui.css"></script>
container-layout.html:	<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
editconfig.html:	<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
hb.html:	<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
image-layout.html:	<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
images.html:	<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
killvip.html:	<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
log.html:	<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
main.html:    <a href="https://github.com/rusher81572/picluster"><img src="/logo.png" height="250" width="250"></a>
nodes.html:	<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
prune.html:	<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
reloadconfig.html:	<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
rsyslog.html:	<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
rsyslog.html:	<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.14.1/moment.min.js"></script>
rsyslog.html:				//	var output = data.replace(/(?:\r\n|\r|\n)/g, '<br />');
running.html:	<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
syslog.html:	<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
syslog.html:	<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.14.1/moment.min.js"></script>
terminal.html:				//$("#command_output").val($('#command_output').val() + '\n' + data + '\n\n$');
```

**Comment by eliasmagn** [comment]
I expect the map file was not merged into 3.9.1 yet: 
```
[root@nas ~]# cat /var/log/nginx/error.log
2017/07/10 21:31:09 [error] 12002#0: *372 open() "/opt/rockstor/static/js/lib/jquery.min.map" failed (2: No such file or directory), client: 192.168.1.219, server: ~^(?<myhost>.+)$, request: "GET /static/js/lib/jquery.min.map HTTP/1.1", host: "192.168.1.183"
2017/07/10 21:42:15 [error] 12002#0: *610 open() "/opt/rockstor/static/js/lib/jquery.min.map" failed (2: No such file or directory), client: 192.168.1.219, server: ~^(?<myhost>.+)$, request: "GET /static/js/lib/jquery.min.map HTTP/1.1", host: "192.168.1.183"
2017/07/10 21:43:01 [error] 12002#0: *631 open() "/opt/rockstor/static/js/lib/jquery.min.map" failed (2: No such file or directory), client: 192.168.1.219, server: ~^(?<myhost>.+)$, request: "GET /static/js/lib/jquery.min.map HTTP/1.1", host: "192.168.1.183"
2017/07/10 21:44:43 [error] 12002#0: *652 open() "/opt/rockstor/static/js/lib/jquery.min.map" failed (2: No such file or directory), client: 192.168.1.219, server: ~^(?<myhost>.+)$, request: "GET /static/js/lib/jquery.min.map HTTP/1.1", host: "192.168.1.183" could be part of bootstrap command 
```


```

**Comment by rusher81572** [comment]
@TokinRing Thank you so much for your contribution! Will merge

**Pull request merged**
